name: CML
on: [push,workflow_dispatch]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: |
          pip install -r requirements.txt
          python train.py  # generate plot.png
          # Create CML report
          cat metrics.txt >> report.md
          echo '![](./plot.png "Confusion Matrix")' >> report.md
          # cml comment create report.md

          if [ "${{ github.event_name }}" == "pull_request" ]; then
            cml comment create report.md
          else
            echo "Not a pull request event. Saving report as an artifact."
            mkdir -p artifacts
            cp report.md artifacts/
          fi
          
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
